### ISSUE TITLE
Getting X and Y values after solving the differential equation for the phase portrait

### ISSUE THREAD

**Issue by sunaina2821** [phaseportrait/phaseportrait#8]
Hey,

Pretty neat library for drawing phase portraits! I was wondering how I can get the X and Y values using the dx/dt and dy/dt differential equations that we provide as an input to get the PhasePortrait2D object. 

Thank you.

**Comment by QuanticPony** [comment]
Hello there,

I want to make sure I understand your query correctly. Are you asking about how to extract a trajectory from the plot or how to generate one?

If your intention is to get a trajectory from the plot for analysis purposes, I would advise against it. Our time integration method prioritizes speed over realism. Our plots should primarily serve as a basic visualization tool and not for in-depth analysis. Currently, there is no built-in functionality in our library to retrieve these values. However, we could consider adding this feature.

If you wish to compute a trajectory starting from a specific point, I recommend utilizing a library such as [scipy.integrate.odeint](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html). You could also use our [Trajectory2D](https://phaseportrait.github.io/reference/phaseportrait/Trajectories2D/) to get a fast trajectory with a [Runge Kutta 3rd](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods) grade integration method.

Hope it helps!

**Comment by sunaina2821** [comment]
Thank you so much for the swift reply!

We basically wanted to generate the trajectory from the plot since my collaborator group wanted to plot it in another software since they are not comfortable with programming, which is why they were basically asking for the X and Y values from the phase portraits. I will try the second option by giving different initial positions. Your suggestions were very helpful.
