### ISSUE TITLE
Pendulum example not working?

### ISSUE THREAD

**Issue by NilssonOpel** [phaseportrait/phaseportrait#9]
Running your pendulum example gives the warning
"/lib/python3.10/site-packages/phaseportrait/streamlines/streamlines_base.py:137: RuntimeWarning: divide by zero encountered in divide
  deltat = np.min(self.get_delta_coordinates(*coords)/(10*np.max(np.abs(_speed))))"
and no plot is produced.

Using python 3.10 on Ubuntu 
$ python3 --version
Python 3.10.12

**Comment by NilssonOpel** [comment]
It is working fine on Windows11, python 10.  So you can close this 

As a note, add a  'pyplot.show()' last in your code, it could have been my problem from the beginning :)

**Comment by Loracio** [comment]
Thank you very much for taking interest in our module! 
Glad to hear your problems are solved :smiley: 

Víctor

**Comment by QuanticPony** [comment]
Updated README to add the `pyplot.show()`. Thanks for the feedback
